alias: "movie end: Chromecast"
trigger:
    platform: state
    entity_id: media_player.loosleyloungecast
    from: 'playing'
condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'group.livingroom'
        state: "on"
      - condition: template
        value_template: '{{ states.light.living_room_lamp.attributes.brightness == 25 }}'
action:
  - service: light.turn_on
    entity_id: group.livingroom
    data:
        brightness_pct: 100
        transition: 10
