alias: "movie start: Netflix"
trigger:
    platform: state
    entity_id: media_player.loosleyloungecast
    to: 'playing'
condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'group.livingroom'
        state: "on"
      - condition: state
        entity_id: input_boolean.moviemode
        state: "on"
      - condition: template
        value_template: "{{ is_state_attr('media_player.loosleyloungecast', 'app_name', 'Netflix') }}"
action:
  - service: light.turn_on
    entity_id: group.livingroom
    data:
        brightness_pct: 10
        transition: 3
