alias: 'Internet Check'
trigger:
  - platform: state
    entity_id: binary_sensor.ping_binary_sensor
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.ping_binary_sensor
    from: 'on'
    to: 'off'
action:
  - service: shell_command.clouldutil
  - delay:
        seconds: 10
  - service: homeassistant.restart
