alias: "Automatic Lights"
trigger:
  - platform: state
    entity_id: group.all_devices
    to: 'home'
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 0
condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    - condition:  numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 0

action:
  - service: homeassistant.turn_on
    data:
      entity_id: group.ikealighting
      brightness: 255
      color_temp: 450
