alias: "Automatic Lights"
trigger:
  - platform: state
    entity_id: group.all_devices
    to: 'home'
  - platform: sun
    event: sunset
    offset: '-00:45:00'
condition:
    condition: state
    entity_id: group.all_devices
    state: 'home'

action:
  - service: light.turn_on
    data:
      entity_id: group.livingroom
      brightness: 255
      color_temp: 450
  - service: light.turn_on
    data:
      entity_id: light.window_lights
      effect: candy cane
      brightness_pct: 50
