alias: "Automatic Lights"
trigger:
  - platform: state
    entity_id: group.all_devices
    to: 'home'
  - platform: state
    entity_id: input_boolean.nightmode
    from: 'off'
    to: 'on'
  - platform: homeassistant
    event: start
condition:
 -  condition: state
    entity_id: group.family
    state: 'home'
 -  condition: state
    entity_id: input_boolean.nightmode
    state: "on"
action:
  - service: light.turn_on
    data:
      entity_id: group.livingroom
      brightness: 255
      color_temp: 450
  - service: light.turn_on
    data:
      entity_id: light.window_lights
      effect: candy cane
      brightness_pct: 50
