alias: "morning"
trigger:
    platform: sun
    event: sunrise
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.nightmode
  - service: notify.twitter
    data:
        message: "\U0001f307 Good Morning \U0001f307"
