alias: "morning"
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: -6
condition:
  - condition: state
    entity_id: sun.sun
    state: above_horizon
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.nightmode

  - service: notify.twitter
    data:
        message: "\U0001f307 Good Morning \U0001f307"
