alias: 'Ioan Enter Bristol'
trigger:
- platform: zone
  entity_id: device_tracker.ioan_phone
  zone: zone.bristol
  event: enter
action:
- service: input_boolean.turn_on
  entity_id: input_boolean.ioanbristol
