# This package conatains all of the componet that relies on internet accsess
# the plan is to rename the file cloud.yaml.down when the internet is down to prevent home assistant
# wasting resorces when the network is down

netatmo:
  api_key: !secret netatmoapikey
  secret_key: !secret netatmokey
  username: !secret netatmoemail
  password: !secret normalpass

sensor:
  - platform: google_travel_time 
    name: Home To Work
    api_key: !secret gmapsapikey 
    origin: zone.home
    destination: zone.work
  - platform: google_travel_time
    name: Time To UWE
    api_key: !secret gmapsapikey
    options:
        mode: transit
    origin: device_tracker.ioan_phone
    destination: zone.uwe
  - platform: rest
    name: pollen
    resource: !secret pollenurl
    value_template: '{{value_json["forecast"][3]["pollen_count"]}}'
    scan_interval: 21600
    headers:
       Referer: "https://www.benadryl.co.uk/social-pollen-count"
  - platform: metoffice
    api_key: !secret metkey
    monitored_conditions:
      - weather
      - temperature
      - feels_like_temperature
      - wind_speed
      - wind_direction
      - wind_gust
      - visibility
      - visibility_distance
      - uv
      - precipitation
      - humidity
  - platform: luftdaten
    sensorid: !secret luftdaten
    scan_interval: 140
    monitored_conditions:
      - P1
      - P2
  - platform: netatmo
    modules:
      Indoor:
        - temperature
        - humidity
      Wombat Outdoor:
        - temperature
      WombatRain:
        - sum_rain_24
        - sum_rain_1

binary_sensor:
  - platform: aurora


weather:
  - platform: metoffice
    api_key: !secret metkey

climate:
  - platform: netatmo
    scan_interval: 10

media_player:
  - platform: spotify
    client_id: !secret spotid
    client_secret: !secret spotsec

notify:
  - name: twitter
    platform: twitter
    consumer_key: !secret twitterck
    consumer_secret: !secret twittercs
    access_token: !secret twitterat
    access_token_secret: !secret twitterats

